default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: kimgelio_development

production:
  <<: *default
  database: kimgelio_development

test:
  <<: *default
  database: kimgelio_test%